### ISSUE TITLE
vue cli安装报错

### ISSUE THREAD

**Issue by sfyr111** [dwqs/vue-typescript#1]
## 执行npm install 报以下错误

> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.2-node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.2 and node@8.4.0 (node-v57 ABI) (falling back to source compile with node-gyp)

## 执行npm run dev 
> npx cross-env NODE_ENV=development node ./build/dev-server.js

---------env------: development ------apiPrefix-------:
module.js:491
    throw err;
    ^

Error: Cannot find module '../dist/vendor-manifest.json'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/yangran/project/vue-ts/build/webpack.dev.config.js:44:17)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/yangran/project/vue-ts/build/dev-server.js:8:24)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-ts@0.0.1 dev: `npx cross-env NODE_ENV=development node ./build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-ts@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by dwqs** [comment]
请看 [Readme](https://github.com/dwqs/vue-typescript/blob/master/template/README.md)
